site_name: Orchard Core Commerce
theme:
  name: material
  custom_dir: docs/theme
  logo: assets/images/orchard-logo.png
  favicon: assets/images/favicon.png
  features:
    - header.autohide
    - navigation.instant
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  static_templates:
    - 404.html

extra:
  social:
    - icon: fontawesome/solid/leaf
      link: https://orchardcore.net
    - icon: fontawesome/brands/github-alt
      link: https://github.com/OrchardCMS/OrchardCore.Commerce
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OrchardCMS

# Repository
repo_name: OrchardCMS/OrchardCore.Commerce
repo_url: https://github.com/OrchardCMS/OrchardCore.Commerce
edit_uri: edit/main/src/

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.b64
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: true

plugins:
  - search
  - git-authors
  - git-revision-date-localized
  - exclude:
      glob:
        # Excluding the large node folder with all its MD files. We can't exclude everything apart from docs because there are links to e.g. C# files too.
        - "*node_modules*"

# Page tree
nav:
  - About: index.md
  - Key Features:
    - Inventory: inventory.md
    - Products and Prices: products-and-prices.md
    - Promotions: promotions.md
    - Stripe Payment: stripe-payment.md
    - Taxation: taxation.md
    - User Features: user-features.md
  - Resources:
    - Libraries: resources/libraries/README.md
  - Releases:
    - 0.0.1: releases/0.0.1.md
    - 1.0.0: releases/1.0.0.md
