name: Crowdin Synchronization

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Lombiq/GitHub-Actions/.github/actions/checkout@dev

      - name: Set up .NET
        uses: Lombiq/GitHub-Actions/.github/actions/setup-dotnet@dev

      - name: Generate and upload localization strings
        shell: pwsh
        run: |
          # Generate latest localization files.
          dotnet tool install --global OrchardCoreContrib.PoExtractor
          New-Item -Path Localization -ItemType Directory
          extractpo . Localization

          # Clone the Translations repository.
          git clone https://github.com/OrchardCMS/OrchardCore.Commerce.Translations.git Remote

          # Update the Translations repository.
          Push-Location Remote
          Move-Item -Force ../Localization/*.pot Localization/
          git add .
          git status
          git commit "--message=Updated .pot files.`n`nhttps://github.com/OrchardCMS/OrchardCore.Commerce/commit/$(git rev-parse HEAD)`n`n$(git log -1)"
          git push
          Pop-Location

          Remove-Item -Recurse -Force Remote, Localization
